<?php
/**
 * Yireo CmsLayouts for Magento
 *
 * @package     Yireo_CmsLayouts
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright 2015 Yireo (http://www.yireo.com/)
 * @license     Open Source License (OSL v3)
 * @link        https://www.yireo.com/
 */
?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Edit'); ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr class="headings">
                <td class="label">
                    <label for="label"><?php echo Mage::helper('cmslayouts')->__('Label')?></label>
                </td>
                <td class="value">
                    <input type="text" name="label" value="<?php echo $this->getEntity()->getLabel(); ?>" />
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<?php echo $this->getChildHtml('mockup_file'); ?>

<script>
    function toggleElementForm(element) {
        $(element).toggle();
    }

    function submitForm(task) {
        $('form_redirect').setValue(task);
        return editForm.submit();
    }
</script>
