<div class="cmslayouts">
    <?= $this->includeElementHtml('example1-banner') ?>

    <div class="example1-columns">
        <div class="column-33">
            <?= $this->includeElementHtml('example1-left') ?>
        </div>
        <div class="column-33">
            <?= $this->includeElementHtml('example1-middle') ?>
        </div>
        <div class="column-33">
            <?= $this->includeElementHtml('example1-right') ?>
        </div>
    </div>
</div>