<?php
/**
 * Yireo CmsLayouts for Magento
 *
 * @package     Yireo_CmsLayouts
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright 2015 Yireo (http://www.yireo.com/)
 * @license     Open Source License (OSL v3)
 * @link        https://www.yireo.com/
 */
?>
<div class="<?= $this->getCode() ?>" id="element-<?= $this->getCode() ?>">
    <div class="inner">
        <?php $elementHtml = $this->getElementHtml(); ?>
        <?php if(!empty($elementHtml)) : ?>
            <?= $elementHtml; ?>
        <?php else: ?>
            <span class="template">Template: <?= $this->getElementTemplate(); ?></span>
        <?php endif; ?>
    </div>
</div>