<div class="cmslayouts">
    <?= $this->getElement('theme-banner') ?>

    <div class="ad-columns">
        <div class="column-33">
            <?= $this->getElement('ad-left-top') ?>
            <div class="ad-left-bottom">
                <?= $this->getElement('ad-left-bottom-1') ?>
                <?= $this->getElement('ad-left-bottom-2') ?>
            </div>
        </div>
        <div class="column-33">
            <?= $this->getElement('ad-product') ?>
        </div>
        <div class="column-33">
            <?= $this->getElement('ad-main') ?>
        </div>
    </div>
    <div style="clear:both"></div>
</div>